export const shopData: Record<string, any> = {
  "seeds-shop": {
    title: "Seeds Shop",
    description: "High-quality seeds for all your farming needs",
    products: [
      {
        id: 1,
        name: "Wheat Seeds",
        price: "₹26.80/Kg",
        image: "",
        description: "Premium quality wheat seeds with high yield",
      },
      {
        id: 2,
        name: "Paddy Seeds",
        price: "₹23.00/Kg",
        image: "",
        description: "Hybrid rice seeds for better production",
      },
      {
        id: 3,
        name: "Corn Seeds",
        price: "₹26/kg",
        image: "",
        description: "Disease-resistant corn seeds",
      },
      {
        id: 4,
        name: "Sugarcane Seeds",
        price: "₹3.0/Kg",
        image: "",
        description: "Sugarcane seeds bundle",
      },
      {
        id: 5,
        name: "Mustard Seeds",
        price: "₹60/kg",
        image: "₹",
        description: "High oil content mustard seeds",
      },
      {
        id: 6,
        name: "Pearl Millet Seeds",
        price: "₹120/kg",
        image: "",
        description: "Various pulse seeds for cultivation",
      },
    ],
  },
  "fertilizer-shop": {
    title: "Fertilizer Shop",
    description: "Quality fertilizers for healthy crops",
    products: [
      {
        id: 1,
        name: "Urea",
        price: "₹267-bag/45kg",
        image: "",
        description: "High nitrogen content fertilizer for enhanced crop growth",
      },
      {
        id: 2,
        name: "Potash",
        price: "₹630-bag/50kg",
        image: "",
        description: "Potassium-rich fertilizer for improved crop quality",
      },
    ],
  },
  "pesticide-shop": {
    title: "Pesticide Shop",
    description: "Effective pesticides for crop protection",
    products: [
      {
        id: 1,
        name: "Insecticide Spray",
        price: "₹350/liter",
        image: "",
        description: "Broad-spectrum insect control",
      },
      {
        id: 2,
        name: "Fungicide",
        price: "₹400/liter",
        image: "",
        description: "Prevents fungal diseases",
      },
      {
        id: 3,
        name: "Herbicide",
        price: "₹300/liter",
        image: "",
        description: "Effective weed control solution",
      },
      {
        id: 4,
        name: "Organic Pesticide",
        price: "₹500/liter",
        image: "",
        description: "Eco-friendly pest control",
      },
      {
        id: 5,
        name: "Rodenticide",
        price: "₹250/pack",
        image: "",
        description: "Rodent control solution",
      },
      {
        id: 6,
        name: "Nematicide",
        price: "₹450/liter",
        image: "",
        description: "Controls nematode infestations",
      },
    ],
  },
  "farming-equipment-shop": {
    title: "Farming Equipment Shop",
    description: "Modern farming equipment and tools",
    products: [
      {
        id: 1,
        name: "Plough",
        price: "₹5,000",
        image: "",
        description: "Heavy-duty plough for soil preparation",
      },
      {
        id: 2,
        name: "Cultivator",
        price: "₹8,000",
        image: "",
        description: "Multi-purpose cultivator",
      },
      {
        id: 3,
        name: "Seed Drill",
        price: "₹12,000",
        image: "",
        description: "Precision seed planting equipment",
      },
      {
        id: 4,
        name: "Harvester",
        price: "₹25,000",
        image: "",
        description: "Manual harvesting tool",
      },
      {
        id: 5,
        name: "Sprayer",
        price: "₹3,500",
        image: "",
        description: "Agricultural sprayer for pesticides",
      },
      {
        id: 6,
        name: "Thresher",
        price: "₹15,000",
        image: "",
        description: "Grain threshing machine",
      },
    ],
  },
  "tractor-shop": {
    title: "Tractor Shop",
    description: "Powerful tractors for all farming operations",
    products: [
      {
        id: 1,
        name: "Mini Tractor 25HP",
        price: "₹3,50,000",
        image: "",
        description: "Compact tractor for small farms",
      },
      {
        id: 2,
        name: "Medium Tractor 40HP",
        price: "₹5,50,000",
        image: "",
        description: "Versatile medium-sized tractor",
      },
      {
        id: 3,
        name: "Heavy Tractor 60HP",
        price: "₹8,00,000",
        image: "",
        description: "High-power tractor for large fields",
      },
      {
        id: 4,
        name: "Tractor Trolley",
        price: "₹75,000",
        image: "",
        description: "Heavy-duty tractor trolley",
      },
      {
        id: 5,
        name: "Rotavator Attachment",
        price: "₹45,000",
        image: "",
        description: "Tractor-mounted rotavator",
      },
      {
        id: 6,
        name: "Tractor Loader",
        price: "₹1,20,000",
        image: "",
        description: "Front-end loader attachment",
      },
    ],
  },
  "irrigation-shop": {
    title: "Irrigation Shop",
    description: "Modern irrigation systems and equipment",
    products: [
      {
        id: 1,
        name: "Drip Irrigation Kit",
        price: "₹8,000",
        image: "",
        description: "Complete drip irrigation system",
      },
      {
        id: 2,
        name: "Sprinkler System",
        price: "₹12,000",
        image: "",
        description: "Automatic sprinkler irrigation",
      },
      {
        id: 3,
        name: "Water Pump",
        price: "₹15,000",
        image: "",
        description: "High-efficiency water pump",
      },
      {
        id: 4,
        name: "PVC Pipes",
        price: "₹150/meter",
        image: "",
        description: "Durable irrigation pipes",
      },
      {
        id: 5,
        name: "Water Tank",
        price: "₹20,000",
        image: "",
        description: "Large capacity water storage",
      },
      {
        id: 6,
        name: "Irrigation Timer",
        price: "₹2,500",
        image: "",
        description: "Automatic irrigation controller",
      },
    ],
  },
};
