export const productDetailData: Record<string, any> = {
  "seeds-shop": {
    title: "Seeds Shop",
    products: [
      {
        id: 1,
        name: "Wheat Seeds",
        price: 26.8,
        unit: "Kg",
        image: "",
        description: "Premium quality wheat seeds with high yield. These seeds are specially selected for their superior germination rate and disease resistance. Ideal for all soil types and climatic conditions.",
        features: [
          "High germination rate (>95%)",
          "Disease resistant variety",
          "Suitable for all soil types",
          "Excellent yield potential",
          "Certified quality seeds",
        ],
      },
      {
        id: 2,
        name: "Paddy Seeds",
        price: 23.0,
        unit: "Kg",
        image: "",
        description: "Hybrid rice seeds for better production with enhanced grain quality and pest resistance.",
        features: [
          "Hybrid variety",
          "High yield potential",
          "Pest resistant",
          "Good grain quality",
          "Suitable for wet cultivation",
        ],
      },
      {
        id: 3,
        name: "Corn Seeds",
        price: 26,
        unit: "kg",
        image: "",
        description: "Disease-resistant corn seeds with excellent yield and quality.",
        features: [
          "Disease resistant",
          "High yield",
          "Good grain quality",
          "Drought tolerant",
          "Fast growing variety",
        ],
      },
      {
        id: 4,
        name: "Sugarcane Seeds",
        price: 3.0,
        unit: "kg",
        image: "",
        description: "Premium sugarcane seeds for high sugar content and better yield.",
        features: [
          "High sugar content",
          "Disease resistant",
          "Good tillering",
          "Suitable for all regions",
          "Long harvesting period",
        ],
      },
      {
        id: 5,
        name: "Mustard Seeds",
        price: 60,
        unit: "kg",
        image: "",
        description: "High oil content mustard seeds for commercial cultivation.",
        features: [
          "High oil content",
          "Disease resistant",
          "Good yield",
          "Suitable for winter season",
          "Premium quality",
        ],
      },
      {
        id: 6,
        name: "Pearl Millet Seeds",
        price: 120,
        unit: "kg",
        image: "",
        description: "Drought-resistant pearl millet seeds for dry regions.",
        features: [
          "Drought resistant",
          "High nutritional value",
          "Good yield",
          "Suitable for dry regions",
          "Fast growing",
        ],
      },
    ],
  },
  "fertilizer-shop": {
    title: "Fertilizer Shop",
    products: [
      {
        id: 1,
        name: "Urea",
        price: 267,
        unit: "Bag/45 kg",
        image: "",
        description: "High nitrogen content fertilizer for enhanced crop growth. Urea is the most widely used nitrogen fertilizer, providing essential nutrients for plant development and increased yield.",
        features: [
          "46% nitrogen content",
          "Quick release formula",
          "Suitable for all crops",
          "Increases crop yield",
          "Cost-effective solution",
        ],
      },
      {
        id: 2,
        name: "Potash",
        price: 630,
        unit: "Bag/50 Kg",
        image: "",
        description: "Potassium-rich fertilizer for improved crop quality and disease resistance. Essential for fruit development, root growth, and overall plant health.",
        features: [
          "High potassium content",
          "Improves fruit quality",
          "Enhances disease resistance",
          "Strengthens plant stems",
          "Increases water efficiency",
        ],
      },
    ],
  },
};
